### ISSUE TITLE
Upon start the guests are erroring with "No bootable device found"

### ISSUE THREAD

**Issue by sebastian-philipp** [kubic-project/kubic-terraform-kvm#5]
@shyukri could you add a screenshot? 

Replaces https://github.com/sebastian-philipp/test-rook-orchestrator/issues/1

**Comment by shyukri** [comment]
![kubic_no_bootable_device](https://user-images.githubusercontent.com/1135475/56943187-00090b00-6b27-11e9-8a54-be37385da395.png)

dumpxml:
```<domain type="kvm" id="3"><name>kubic-kubadm-0</name><uuid>fb830157-57a3-4296-b83a-08a30e92a68f</uuid><memory unit="KiB">2097152</memory><currentMemory unit="KiB">2097152</currentMemory><vcpu placement="static">2</vcpu><resource><partition>/machine</partition></resource><os><type arch="x86_64" machine="pc-i440fx-3.1">hvm</type><boot dev="hd"/></os><features><acpi/><apic/><pae/></features><cpu mode="host-passthrough" check="none"/><clock offset="utc"/><on_poweroff>destroy</on_poweroff><on_reboot>restart</on_reboot><on_crash>destroy</on_crash><devices><emulator>/usr/bin/qemu-system-x86_64</emulator><disk type="volume" device="disk"><driver name="qemu" type="qcow2"/><source pool="default" volume="os_volume-0"/><backingStore type="file" index="1"><format type="qcow2"/><source file="/var/lib/libvirt/images/kubic_image"/><backingStore/></backingStore><target dev="vda" bus="virtio"/><alias name="virtio-disk0"/><address type="pci" domain="0x0000" bus="0x00" slot="0x05" function="0x0"/></disk><disk type="volume" device="disk"><driver name="qemu" type="qcow2"/><source pool="default" volume="data_volume-0"/><backingStore/><target dev="vdb" bus="virtio"/><alias name="virtio-disk1"/><address type="pci" domain="0x0000" bus="0x00" slot="0x06" function="0x0"/></disk><disk type="file" device="cdrom"><driver name="qemu" type="raw"/><source file="/var/lib/libvirt/images/commoninit-0.iso"/><backingStore/><target dev="hda" bus="ide"/><readonly/><alias name="ide0-0-0"/><address type="drive" controller="0" bus="0" target="0" unit="0"/></disk><controller type="usb" index="0" model="piix3-uhci"><alias name="usb"/><address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x2"/></controller><controller type="pci" index="0" model="pci-root"><alias name="pci.0"/></controller><controller type="ide" index="0"><alias name="ide"/><address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x1"/></controller><controller type="virtio-serial" index="0"><alias name="virtio-serial0"/><address type="pci" domain="0x0000" bus="0x00" slot="0x04" function="0x0"/></controller><interface type="network"><mac address="52:54:00:76:bf:99"/><source network="default" bridge="virbr0"/><target dev="vnet2"/><model type="virtio"/><alias name="net0"/><address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x0"/></interface><channel type="pty"><source path="/dev/pts/3"/><target type="virtio" name="org.qemu.guest_agent.0" state="disconnected"/><alias name="channel0"/><address type="virtio-serial" controller="0" bus="0" port="1"/></channel><input type="mouse" bus="ps2"><alias name="input0"/></input><input type="keyboard" bus="ps2"><alias name="input1"/></input><graphics type="spice" port="5902" autoport="yes" listen="127.0.0.1"><listen type="address" address="127.0.0.1"/></graphics><video><model type="cirrus" vram="16384" heads="1" primary="yes"/><alias name="video0"/><address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0"/></video><memballoon model="virtio"><alias name="balloon0"/><address type="pci" domain="0x0000" bus="0x00" slot="0x07" function="0x0"/></memballoon><rng model="virtio"><backend model="random">/dev/urandom</backend><alias name="rng0"/><address type="pci" domain="0x0000" bus="0x00" slot="0x08" function="0x0"/></rng></devices>```

tox output (with bash -ex)
[tox.txt](https://github.com/kubic-project/kubic-terraform-kvm/files/3130093/tox.txt)

**Comment by sebastian-philipp** [comment]
@shyukri do you have the kubic_image properly imported?  
```
$ file /var/lib/libvirt/images/kubic_image
/var/lib/libvirt/images/kubic_image: QEMU QCOW Image (v3), 25769803776 bytes
```

**Comment by MalloZup** [comment]
@sebastian-philipp @shyukri update to latest `terraform-libvirt` master it should be fixed

**Comment by sebastian-philipp** [comment]
@shyukri : please reopen, if unresolved.
